### ISSUE TITLE
If Ulfius support to fork?

### ISSUE THREAD

**Issue by xiao8385** [babelouest/ulfius#100]
Hi,
Thank you very much if you can help to reply my question.

Currently we use simple way to create socket server and fork it to listen multi clients' request.
`    int err = getaddrinfo(hostname, portname, &hints, &res);
`

We want to use Ulfius to implement Web socket server. So I want to ask if we can fork in callbackXXX() function to clone itself? The purpose is to keep only one port to client.

Below is our code screenshot for your reference, we worried about if it is thread safe.

`int callback_get_test (const struct _u_request * request, struct _u_response * response, void * user_data) {
   pid_t pid = fork();
   if ( pid < 0 )
   {
	exit(1);
   }
   else if (pid == 0 )
   {    
     return U_CALLBACK_CONTINUE;
   }
   else
   {
	waitpid(pid, &stat, 0);
	return 0;
   }
}`

**Comment by babelouest** [comment]
I'm not sure it would work but I haven't tried.

The problem is Ulfius opens a new thread on each incoming connection, so if you fork within a thread, all other threads will be forked too.

Also, I don't understand why you worry about thread-safe if you want to fork the program. But I must admit I'm not that much into deep system programming so I may be mistaken.

**Comment by babelouest** [comment]
Hello @xiao8385 ,

Have you tried your fork call within the callback function?

**Comment by xiao8385** [comment]
Hi @babelouest ,

Sorry reply you too late as we are in public holiday.

Yes, we tried with the demo and it works. 
But we have to consider there are too many static variables in our code (will share in different child-process), which may cause thread safe issue. And consider the child-process is under the thread, we are not sure if it will be under control for all statements.

So we propose a workflow to use Ulfius with multi-process between the client and Ulfius server.
1.	Create a dispatcher that is also Ulfius server which port (PORT) will publish to client to use
2.	Configure a max concurrency support number (X)
3.	Based on the max number to setup X of same Ulfius servers with different port (PORT[1…x])
4.	Start sequence is PORT[1…x] first, then PORT
5.	PORT, PORT[1], … , PORT[x] start with different process id
6.	Client send request to dispatcher
        1)	Dispatcher connect to PORT[1]
                > Success, TBC
                > Failed, move to next step
        2)	…
        3)	Dispatcher connect to PORT[x]
                > Success, TBC
                > Failed, wait and move to step 6.1

**Comment by babelouest** [comment]
Hello @xiao8385 ,

Happy new year!

Considering using Ulfius in a fork context could lead to bugs that would be difficult to fix, I have another suggestion, you can try to use [libmicrohttpd](https://www.gnu.org/software/libmicrohttpd/) instead of Ulfius. Ulfius is based on libmicrohttpd for the low-level http management, but libmicrohttpd has more options available. For example, you could use the flag `MHD_USE_SELECT_INTERNALLY` in `MHD_start_daemon` so only one thread will be executed in runtime.

https://www.cs.du.edu/~chrisg/classes/06/comp3621/check1.html
https://www.gnu.org/software/libmicrohttpd/manual/html_node/microhttpd_002dconst.html

Not that I don't want you to use Ulfius, but maybe it isn't the best choice for your requirements.

If you really need to use Ulfius, you can modify its code to fit your needs, like changing `ulfius_run_mhd_daemon`: https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L775
and disabling the websockets so no other threads will be executed on runtime.
Nevertheless, changing Ulfius `ulfius_run_mhd_daemon` function is not recommended by me since I can't guarantee everything will work as expected.
