### ISSUE TITLE
[Issue] Building ulfius with websockets and without TLS fails

### ISSUE THREAD

**Issue by stefvanos** [babelouest/ulfius#125]
**Describe the issue**
building ulfius without U_DISABLE_WEBSOCKET and with U_DISABLE_GNUTLS fails.
There is no ifdef guarding for this in ulfius.h and u_websocket.c

**To Reproduce**
configure ulfius to build with websockets and without tls support

**Expected behavior**
Building ulfius with plain ws:// websockets without TLS

**Comment by stefvanos** [comment]
A I see that this is a known limitation.
Would it make sense if I send a PR to make this possible? Or is it a deliberate design choice to not support this combination?
BR,
Stef

**Comment by babelouest** [comment]
Yes, as stated in the [installation documentation](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#manual-install), by design, GnuTLS is required for websockets, even in `http` mode.

Although if you want, you can patch the code by yourself to remove this dependency and allow to use websockets (server and client). I won't endorse those changes though.

AFAIR, there are 3 uses of GnuTLS in Ulfius websocket source code:

- Generate random bytes for the message mask and the key: https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L226 - https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L1449
  => You can use `rand()` instead of `gnutls_rnd()`. (don't forget to `rseed()`!), or any other random number generator you want.

- Create a hash of the the key and the magick string using SHA1 as part of the handshake validation: https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L874
  => You must use another function to hash the key in SHA1. A quick search says [this is possible](https://gist.github.com/jrabbit/1042021), although I haven't tested.

- Handle TLS connections for websocket client: https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L716 - https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L72 - https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L103 - https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L1009
  => Since you won't use websocket in TLS mode, you can simply (and carefully) remove those lines

But I won't make the change in my Ulfius repository to be able to use websockets without GnuTLS, Mostly because of the first 2 uses.

Hope that helps.

Happy hacking!
