### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by doragasu** [babelouest/ulfius#14]
I have been recently searching for a small REST implementation preferably coded in C, and this one looks promising. It looks like it supports everything I need, and as it uses libmicrohttpd, I suppose it also supports HTTPS.

But I have not been able to find information about how to use HTTPS with ulfius. Is it supported? If affirmative, are there any examples or directions I can follow to get HTTPS working with ulfius?

**Comment by babelouest** [comment]
Yes, it does support https, you need to use `ulfius_start_secure_framework` instead of `ulfius_start_framework` and give the private key and the certificate:
https://github.com/babelouest/ulfius/blob/master/API.md#start-webservice
```c
/**
 * ulfius_start_secure_framework
 * Initializes the framework and run the webservice based on the parameters given using an HTTPS connection
 * 
 * u_instance:    pointer to a struct _u_instance that describe its port and bind address
 * key_pem:       private key for the server
 * cert_pem:      server certificate
 * return U_OK on success
 */
int ulfius_start_secure_framework(struct _u_instance * u_instance, const char * key_pem, const char * cert_pem);
```

There is a minimal example in the `simple_example` program:
https://github.com/babelouest/ulfius/blob/master/examples/simple_example/simple_example.c

**Comment by doragasu** [comment]
Thank you very much for the fast and complete response!
