### ISSUE TITLE
undefined reference to symbol 'o_free'

### ISSUE THREAD

**Issue by alexe100** [babelouest/ulfius#147]
Hi! Nice job!
I am trying to compile a sample that responds to POST where json info is passed through http body. On callback I am trying to use the print_map() in order to get it as a string.  I see compilation error for o_free bu also to o_strlen, etc.
Why?

What is the difference between o_malloc and malloc? Can I rewrite print_map() function in order to use malloc and free or are there any sided effect? Which  header should I use n order to solve the problem?

Thank you

Alex

**Comment by alexe100** [comment]
-lorcania

**Comment by babelouest** [comment]
You figured out by yourself to link to [orcania library](https://github.com/babelouest/orcania) :)

Quick answer about `o_malloc` and all `o_*` functions, they are part of the orcania library.

The string-related functions (`o_strcpy`, `o_strlen`, etc) are similar to their `<string.h>` functions, except you can use them with `NULL` parameters without getting a seg fault.
https://babelouest.github.io/orcania/doc/html/group__str.html

The memory functions `o_malloc`, `o_realloc` and `o_free` can be used to replace the libc functions `malloc`, `realloc` and `free` with your own memory functions, otherwise, they are simple mappings for the libc ones.
https://babelouest.github.io/orcania/doc/html/group__mem.html
