### ISSUE TITLE
Node-Red can't connect to Ulfius websocket server

### ISSUE THREAD

**Issue by oliv3** [babelouest/ulfius#152]
[Node-red](https://nodered.org/) websocket node can not connect to an embedded server, (based on websocket_server.c), when Ulfius websocket client (websocket_client.c) can.

Here's webclient_client handshaking with the application:

```
GET websocket HTTP/1.1
Host: adoy
Upgrade: websocket
Connection: Upgrade
Origin: ws://adoy
Sec-WebSocket-Protocol: protocol
Sec-WebSocket-Extensions: extension
Sec-WebSocket-Version: 13
Upgrade: websocket
Connection: Upgrade
Content-Length: 0
User-Agent: Ulfius Websocket Client Framework/2.5.2
Sec-WebSocket-Key: bVI2azg5SHNvUWtmcnRuTw==

HTTP/1.1 101 Switching Protocols
Access-Control-Allow-Origin: *
Sec-WebSocket-Protocol: protocol
Sec-WebSocket-Accept: CcJZs4M5zALyX0R/CwpOY+IFUJM=
Upgrade: websocket
Connection: Upgrade
Date: Thu, 02 Jan 2020 18:01:04 GMT
```

And this is Node-Red trying to connect:
```
GET /websocket HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 3GYU7JVtQdSscRZbNtB3rw==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: adoy:30544

HTTP/1.1 400 Bad Request
Content-Length: 0
Date: Thu, 02 Jan 2020 18:00:56 GMT
```

Is this a bug in Ulfius or Node-Red ?

Thanks anyway for this great framework !

**System:**
 - OS/Environment [Debian/sid]
 - Ulfius Version [2.5.2-4+b1]
 - Source installation [Debian package]

**Comment by babelouest** [comment]
Hello,

If you enable yder-logging in DEBUG mode, you should see a debug message with the reason why the websocket handshake failed

```C
// Add -lyder to your gcc linker option

#include <yder.h>

y_init_logs("websocket", Y_LOG_MODE_CONSOLE, Y_LOG_LEVEL_DEBUG, NULL, "Starting websocket server");

// Put your ulfius code here
// ulfius_init_instance():
// ulfius_start_instance();
// etc.

y_close_logs();
```

**Comment by babelouest** [comment]
Not sure if that's the reason but I see that node-red isn't sending a `sec-websocket-extension` and the `sec-websocket-protocol` value is different from the reference above. Maybe the reason lies around that.

When you use `ulfius_set_websocket_response`, you can set both `websocket_protocol` and `websocket_extensions` to `NULL` to avoid ulfius websocket service checking those values.

**Comment by oliv3** [comment]
Hi @babelouest, thanks for the quick response !
I'm afraid this is already so (I mostly cut/pasted websocker_server.c in this POC):
```
  if ((ret = ulfius_set_websocket_response(response, NULL, NULL, &websocket_manager_callback, websocket_user_data, &websocket_incoming_message_callback, websocket_user_data, &websocket_onclose_callback, websocket_user_data)) == U_OK) {
```
So, websocket_protocol and websocket_extensions are already NULL.
Haven't checked the yder part, will let you know.

**Comment by oliv3** [comment]
Here's what I get using debug:

```
2020-01-03T02:53:47 - websocket INFO: Starting websocket server
2020-01-03T02:53:49 - websocket DEBUG: Ulfius - Error websocket connection: 
2020-01-03T02:53:49 - websocket DEBUG: Ulfius - Error websocket connection: 
2020-01-03T02:53:52 - websocket DEBUG: Ulfius - Error websocket connection: 
2020-01-03T02:53:52 - websocket DEBUG: Ulfius - Error websocket connection:
```

**Comment by oliv3** [comment]
Looks like
`y_log_message(Y_LOG_LEVEL_DEBUG, "Ulfius - Error websocket connection: %s", response_buffer);` has an empy response_buffer ?

**Comment by babelouest** [comment]
Hello,

I think you found how to divide by 0 with ulfius :)

There is a bug in the error message [here](https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L650)
Also, there is a typo [there](https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L651) but that's not related

So according to my code, I think node-red websocket connection is rejected because there's no `Origin` in the headers when node-red is making the handshake.

But then I went back to the websocket RFC and its [Client Requirements](https://tools.ietf.org/html/rfc6455#section-4.1) for the websocket handshake, and it states that:

> The request MUST include a header field with the name |Origin| [...]

Ah ha!

> if the request is coming from a browser client. [...]

Oh?

> If the connection is from a non-browser client, the request MAY
> include this header field if the semantics of that client match
> the use-case described here for browser clients.

Aaaaahhhhhhh......

I misread the RFC (not the first time though...).

I [pushed a patch](https://github.com/babelouest/ulfius/commit/4fbe36eaee49685f06c0401ab19b256bf76ff81f) in the master branch, can you test it?

You need to upgrade [orcania](https://github.com/babelouest/orcania) and [yder](https://github.com/babelouest/yder) too.

**Comment by oliv3** [comment]
Hi, just tested: Node-Red connects, great ! But my app segfaults right after (basically the same code as websocket_server.c):

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strncmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101	../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.
[Current thread is 1 (Thread 0x7f3b3f7fe700 (LWP 93086))]
(gdb) bt
#0  __strncmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x00005611992819cf in websocket_manager_callback (request=0x7f3b200086f0, websocket_manager=0x7f3b20008550, websocket_manager_user_data=0x7f3b20008490) at bulfius_websockets.c:71
#2  0x00007f3b574185b8 in ulfius_thread_websocket_manager_run () from /usr/local/lib/libulfius.so.2.6
#3  0x00007f3b573effb7 in start_thread (arg=<optimized out>) at pthread_create.c:486
#4  0x00007f3b573212cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Line 71:
```
  if (strncmp(u_map_get(request->map_header, "User-Agent"), U_WEBSOCKET_USER_AGENT, strlen(U_WEBSOCKET_USER_AGENT)) == 0 &&
```

Node-Red doesn't seem to send a `User-Agent` header, can this explain ? Commenting this part solves the problem obviously, but is Ulfius supposed to crash on this ?

Even with this connected, Node-Red gets disconnected after a few seconds, I'll investigate this.

**Comment by babelouest** [comment]
Probably because you use `strncmp` instead of `o_strncmp`, `u_map_get(request->map_header, "User-Agent")` returns NULL, therefore your program crashes.

You can remove those lines, it's just a way to avoid sending fragmented messages to browsers since [they seem not to like it](https://github.com/babelouest/ulfius/blob/master/API.md#fragmented-messages-limitation-in-browsers).

But in general, if you use `str*` functions, you need to verify all the parameters are not NULL, otherwise you can use [Orcania](https://github.com/babelouest/orcania) functions that are created to avoid that.

**Comment by oliv3** [comment]
Ok, thanks, hadn't looked at Orcania yet.
According to tcpdump, Ulfius sends a text FIN followed by a binary FIN, I probably have to dive more in the documentation :)
Thanks anyway for the fix, will it land in Debian/sid soon ?

**Comment by babelouest** [comment]
>  According to tcpdump, Ulfius sends a text FIN followed by a binary FIN, I probably have to dive more in the documentation :)

What about it?

>  Thanks anyway for the fix, will it land in Debian/sid soon ?

I should get back to that soon yes ;)

**Comment by oliv3** [comment]
> > According to tcpdump, Ulfius sends a text FIN followed by a binary FIN, I probably have to dive more in the documentation :)
> 
> What about it?

It was simply the websocket manager doing nothing then exiting :)

> 
> > Thanks anyway for the fix, will it land in Debian/sid soon ?
> 
> I should get back to that soon yes ;)

Great ! Again, great job; I think  this issue can be closed now, everything is ok here.

**Comment by babelouest** [comment]
Closing the issue then, thanks for the report!

**Comment by oliv3** [comment]
You're very welcome !
