### ISSUE TITLE
websocket bugfixes

### ISSUE THREAD

**Issue by wouher** [babelouest/ulfius#163]
Hi Nicolas,

While using the websocket functionality in src/u_websocket.c, I encountered 3 issues:

In function `read_data_from_socket`, the data pointer is not increased when running through the do/while loop multiple times. I adjusted it like this:

![image](https://user-images.githubusercontent.com/9251637/82191164-6b6c7900-98f2-11ea-80a5-a700601912f0.png)

Also, in function `read_data_from_socket`, when running through the `do/while` loop multiple times, I think there should be an additional `poll` on the file descriptor (or some handling of EAGAIN when reading the file descriptor).
It is checked the before calling the `read_data_from_socket` function if data is available, but on repeated reads it can happen data is not yet available.
I preferred to solve this by calling `is_websocket_data_available` before every read in the loop with a timeout protection but maybe you have a better way.

In function `ulfius_build_frame`, I think there is an off-by-one error:
![image](https://user-images.githubusercontent.com/9251637/82191295-9a82ea80-98f2-11ea-99c1-06f67a306727.png)

**Comment by babelouest** [comment]
Hello @wouher ,

Thanks for pointing out!

Can you send a Pull Request rather than sending screenshots of your fixes? It'd be easier for me, and I'd understand your second point about the missing `poll`.

If you don't know how to make pull request, you have online documentation to help you, like [this one](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).
