### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Omicron360** [babelouest/ulfius#18]
Bonjour,

J'utilise en ce moment Ulfius et il est très pratique, un petit bijou qui m'a éviter de perdre beaucoup de temps à chercher une solution pour faire une simple requête JSON sur un WebService.
Seulement je me vois confronter à un problème, lorsque mon code sera mise en production il faudra passer par un proxy et je n'ai rien trouvé sur ce sujet dans l'API.
Serais je passé à coté? Est-ce qu'il y a une solution de prévu que je n'aurais pas vu?

Cordialement

**Comment by babelouest** [comment]
Hello,

I'll switch to English since it's the language used in this project.

I'm not sure I understand your question though. There is no restriction to put a webservice behind a proxy wether it's ulfius powered or not, the webservice will act pretty normally. In my case, I have all my applications behind an [apache mod_proxy](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) without any problem.

For example, if you have a webservice running with ulfius on port 8080 on a machine called `hidden`, the mod_proxy configuration could be:

```
ProxyPass /webservice/ http://hidden:8080/
ProxyPassReverse /webservice/ http://hidden:8080/
```

The only change I made in my server code is to use the [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For) header instead of `struct _u_request.client_address` to get the client IP address.

**Comment by Omicron360** [comment]
hello,

I'm sorry, i forgot precise you Ulfius is in client mode behind a proxy.

**Comment by babelouest** [comment]
You're right, Ulfius doesn't handles proxy in client mode yet. I'll add it to the next release 2.1 in preparation.

Thanks for the report!

**Comment by Omicron360** [comment]
Can I ask you when it's ready?

**Comment by babelouest** [comment]
Ready is a string word, but I'll add it in the branch [2.1](https://github.com/babelouest/ulfius/tree/2.1) soon, you can test it in a few days top and send me feedbacks if you see some problems. It will be a simple mapping of [CURL_OPT_PROXY](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html) with the same syntax, so it shouldn't be long.

The version 2.1 will be released as soon as possible, any help to test it is welcome. :)

I'll let you know when it will be available in the beta branch.

**Comment by babelouest** [comment]
You can test it in the branch 2.1:

```
$ git checkout 2.1
$ make && sudo make install
```

A variable `proxy` has been added to the `_u_request` structure. You set it with the proxy address, for example:

```c
struct _u_request request;
struct _u_response response;

ulfius_init_request(&request);
ulfius_init_response(&response);
request.http_url = strdup("http://server.url/");
request.proxy = strdup("http://proxy.url/");
if (ulfius_send_http_request(&request, &response) == U_OK) {
  printf("response status is %d\n", response.status);
}
```

**Comment by babelouest** [comment]
Hi @Omicron360 ,

Any update on the patch?

**Comment by babelouest** [comment]
The patch has been merged in the master branch. Feel free to open a new issue if you find some problems.
