### ISSUE TITLE
 Segmentation fault

### ISSUE THREAD

**Issue by jfory** [babelouest/ulfius#186]
**Describe the issue**
Segmentation Error,  
It's crash using  the  webscket function when long term runing.
It can work. but it will be be crashed after  long term runing.
**Screenshots    corefile Info**
Program terminated with signal SIGSEGV, Segmentation fault.
#0  MHD_destroy_post_processor (pp=0x600000001) at postprocessor.c:1267
1267      if (PP_ProcessValue == pp->state)
[Current thread is 1 (Thread 0x7fd48ffff700 (LWP 15367))]

**System (please complete the following information):**
 - OS/Environment  Ubuntu 16.04, MSVC]
 - Ulfius Version [e.g. 2.7.1]
 - Source installation [build from source]
 -

**Comment by babelouest** [comment]
Hello @jfory ,

I suppose you have built ulfius from source because there's no ulfius 2.7.1 package for Ubuntu 16.04. The first problem is the [libmicrohttpd package](https://packages.ubuntu.com/xenial/libmicrohttpd10) provided in Ubuntu 16.04, it's too old to allow websockets with Ulfius.

I suggest you try with the current LTS version, [libmicrohttpd package](https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=libmicrohttpd) version will allow websockets, and you can also install the packages from this repository: https://github.com/babelouest/ulfius/releases/tag/v2.7.1

**Comment by babelouest** [comment]
Hello @jfory ,

Any update on your issue?

**Comment by babelouest** [comment]
Closing this issue

**Comment by jfory** [comment]
Yes ,it's working after update OS
