### ISSUE TITLE
Testing of ulfius release on centos machines

### ISSUE THREAD

**Issue by ashishsaxenahsc** [babelouest/ulfius#191]
Hi @babelouest,

We are able to compile ulfius on Centos8 machine , but couldn't find any precompiled rpm files for centos in the following release:
https://github.com/babelouest/ulfius/releases/tag/v2.7.2

We just want to know if latest release of ulfius has been tested for Centos machines?

Thanks and Regards,
Ashish

**Comment by babelouest** [comment]
Hello @ashishsaxenahsc ,

I don't provide Centos packages (yet?) because I don't use rpm-based distribs, so I don't know them as much as deb-based distribs.

To me, RPM packages are more difficult to provide because the package names can vary between distributions, [for example](https://github.com/babelouest/huddersfield/blob/master/ulfius/build/rpm/Dockerfile#L13).

So to help me with Centos, can you provide the package dependency list you need to install ulfius?
Especially the development packages for `libmicrohttpd`, `jansson`, `gnutls`, `libcurl`, `zlib` and `libsystemd` (if applicable)

When I have some time, I'll work on adding Centos to my supported distribs for my packages.

**Comment by ashishsaxenahsc** [comment]
Hi Nicholas,

Thanks for your reply.

 I had raised the issue to confirm that ulfius is stable on Centos and there are no known issues, as release folder contai precompiled packages for all other linux distros .

The following packages are required to installed as  dependencies for installing ulfius on the machine:

yum install -y jansson-devel libcurl-devel gnutls-devel zlib-devel systemd-devel
yum --enablerepo=PowerTools install libmicrohttpd-devel

Thanks and Regards,
Ashish

**Comment by babelouest** [comment]
Thanks for the the help @ashishsaxenahsc !

Lucky me centos build is close to fedora's, and with your help with `PowerTools` I could easily build packages for Centos 8: https://github.com/babelouest/ulfius/releases/tag/v2.7.2

Can you test the new package and give me feedbacks for them?

**Comment by babelouest** [comment]
@ashishsaxenahsc , any update?

**Comment by babelouest** [comment]
Due to lack of feedback, I'm closing this issue, feel free to open another if needed.
