### ISSUE TITLE
Client not able to connect to HTTPS server using ulfius framework

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [babelouest/ulfius#193]
We are using ulfius framework for creating a rest server. We have used the function

ulfius_start_secure_framework

to start the framework and run the webservice based on the parameters given using an HTTPS connection. We have supplied key_pem (key.pem) and cert_pem (cert.pem) as input parameters. The server comes up successfully.

Now we have written a client that tries to send request to the above instantiated server. We are using 

ulfius_send_http_request

and set following request properties : -

ulfius_set_request_properties(&request,
                                    U_OPT_HTTP_VERB, "GET",
                                    U_OPT_HTTP_URL, <url>,
                                    U_OPT_NETWORK_TYPE, U_USE_ALL,
                                    U_OPT_CHECK_SERVER_CERTIFICATE, 1,
                                    U_OPT_CLIENT_CERT_FILE, <path to cert.pem used in ulfius_start_secure_framework>,
                                    U_OPT_NONE);

When I try to run my client it is not able to connect to the server. Whereas, if I try to connect to the server via curl command, I am able to connect to it : -

curl --cacert <path to cert.pem used in ulfius_start_secure_framework> -X GET <url>

Is there any issue while setting the request properties in the client?

**Comment by babelouest** [comment]
Hello @ChinmayaAgarwal ,

From what I can see on your sample code, you set `U_OPT_CHECK_SERVER_CERTIFICATE` to 1, which may cause the problem on your side, depending on your certificate configuration and the certificate you are using.

If you enable log messages with `yder`, do you have additional information?

See https://github.com/babelouest/ulfius/blob/master/example_programs/simple_example/simple_example.c#L102 and https://github.com/babelouest/ulfius/blob/master/example_programs/simple_example/simple_example.c#L150 to open and close yder logs, you also must add `-lyder` to your linking options

**Comment by babelouest** [comment]
Hello @ChinmayaAgarwal ,

Any update on this issue?

**Comment by ashishsaxenahsc** [comment]
Hi Nicolas,

After enabling the yder logging , I am getting the following error logs at the client side:

2021-05-24T14:32:18Z - dev_mgmt ERROR: Ulfius - Error curl_easy_perform
2021-05-24T14:32:18Z - dev_mgmt DEBUG: Ulfius - libcurl error: 60, error message 'Peer certificate cannot be authenticated with given CA certificates'

**Comment by oliv3** [comment]
That's what I was thinking first, are you using a self-signed certificate ? If yes, try with e.g. Let's encrypt ?

**Comment by ashishsaxenahsc** [comment]
Yes ,I am using the steps mentioned in auth_example to generate the self-signed server and client certificates:
 
Server key and certificate
 openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt

 Certificate authority
 openssl genrsa -out ca.key 4096
 openssl req -new -x509 -days 365 -key ca.key -out ca.crt

  Client Key and CSR
  openssl genrsa -out client.key 4096
  openssl req -new -key client.key -out client.csr
  openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt

Am I doing something wrong here ?
Also, can you please let me know how to use Let's encrypt in our context ?

Thanks and Regards,
Ashish

**Comment by babelouest** [comment]
You're not doing anything wrong @ashishsaxenahsc , but the error you receive is because your self signed certificate doesn't come from a known source. A workaround for this case is to set the option `U_OPT_CHECK_SERVER_CERTIFICATE` to `0`.

**Comment by ashishsaxenahsc** [comment]
If we are setting U_OPT_CHECK_SERVER_CERTIFICATE to 0 , then we can send the GET request even without providing the certificate in the options. So basically we are sending the GET request without support for TLS. Is this understanding correct ?

Can you please tell me if ulfius have no support for self-signed certificate generated using openssl ?

**Comment by babelouest** [comment]
The option `U_OPT_CLIENT_CERT_FILE` is when you use TLS client authentication. I suppose you don't need it.

In your case, my intuition is that this command will be enough:

```C
ulfius_set_request_properties(&request,
U_OPT_HTTP_VERB, "GET",
U_OPT_HTTP_URL, "<your_url>",
U_OPT_NETWORK_TYPE, U_USE_ALL,
U_OPT_CHECK_SERVER_CERTIFICATE, 0,
U_OPT_NONE);
```

**Comment by ashishsaxenahsc** [comment]
I have compiled the auth_server and auth_client program in example folder present in the ulfius repo . and I have generated the client and server certificate as mentioned in the files. Now , both auth_server and auth_client are running on the same machine., and following is the output of client program:
.
/auth_client client.crt client.key
2021-05-31T18:38:45Z - auth_client INFO: logs start
Press <enter> to run client certificate authentication test

status is
200

string body is
client dn: 'C=XX,L=Default City,O=Default Company Ltd,CN=device_1', ussued by: 'C=XX,L=Default City,O=Default Company Ltd,CN=device_1'

I tried to capture the wireshark logs on the transaction , and from the logs , it is observed that no certificate is send from either side:
![wiresharl_logs](https://user-images.githubusercontent.com/43564844/120263540-828dc700-c2b9-11eb-9b88-a4957cc314e3.png)


As per the tls rfc , I must see the server certificate in the wireshark logs ,even if I am not authenticating client authentication. Can you please let me know I have run the programs in right way , or am I doing anything wrong here , as I am expecting to see server certtificate in the server hello , which is not present here.

Thanks and regards,
Ashish

**Comment by babelouest** [comment]
@ashishsaxenahsc , I'm not sure I understand what you are expecting to do with Ulfius framework, can you enlighten me?

The original issue was about using `ulfius_send_http_request` to make an https connection to a web server that uses a self-signed certificate.

But out of nowhere, you mention an authentication with a client TLS certificate, which isn't the same problem as the server certificate.

Can you explain what you are trying to achieve?

**Comment by babelouest** [comment]
@ashishsaxenahsc , any update?

**Comment by ChinmayaAgarwal** [comment]
Our initial intent was to enable HTTPS message exchange between REST client and a REST server running on the same machine. For this, we were initially trying both client side and server side authentication. But by configuring as per your suggestion, we disabled the client side authentication.
Now, with server side authentication, we were expecting that for server side authentication, the initial handshake from client to server will have the server side certificate. We didn't see it in the wireshark dump. On further study, we found one reference which said that TLS-PSK authentication doesn't require a server side certificate but there should be an exchange for pre-shared keys. Somehow, even that is not seen in our wireshark dumps. Or we are not looking at the right place.

The traffic after the initial handshake is encrypted. But even without passing server side certificate from the client, it shows encrypted traffic. Maybe lack of knowledge, but could you provide some pointers on how to verify that HTTPS is working fine for us.

Thanks and Regards,
Chinmaya Agarwal

**Comment by babelouest** [comment]
There's a difference between an HTTPS connection and an HTTPS connection with client TLS authentication.

With HTTPS, the server provides a way for the clients to connect using a encrypted connection, so that the communication between the client and the server, if listened, would be useless for the listener, because it couldn't decrypt the messages.
https://en.wikipedia.org/wiki/HTTPS#Overview

But HTTPS isn't about client authentication, only securing a communication channel.
The only authentication it can provide is for the client to make sure the server is the one it says, not a man-in-the-middle attack, by using the server certificate
https://en.wikipedia.org/wiki/HTTPS#Security

Then, Client TLS authentication is a way for a client to authenticate itself by using a TLS certificate, the server must recognize the certificate used by the client. A Client TLS authentication is on top of a HTTPS connection.
https://en.wikipedia.org/wiki/Mutual_authentication

> Our initial intent was to enable HTTPS message exchange between REST client and a REST server running on the same machine.

To do so, you need to use `int ulfius_start_secure_framework(struct _u_instance * u_instance, const char * key_pem, const char * cert_pem);` to run an HTTPS webservice.

The parameter `key_pem` is the private key and `cert_pem` is the corresponding certificate. To generate a self-signed certificate, you can check online documentation for lots of examples, like https://letsencrypt.org/docs/certificates-for-localhost/

If you need an HTTPS certificate signed by a well-known authority, you can use a letsencrypt certificate for example: https://letsencrypt.org/getting-started/

> Now, with server side authentication, we were expecting that for server side authentication, the initial handshake from client to server will have the server side certificate

When you use a HTTPS connection, the client retrieves and verifies the server certificate. Although when you use Ulfius' `ulfius_send_http_request`, even if the server certificate is verified by default, you can't get the server certificate data for now, maybe I'll add this feature later.

> TLS-PSK authentication doesn't require a server side certificate

This is partially true, for the client authentication side only, but since a TLS-PSK authentication must be on top of an HTTPS connection, you'll need a server certificate anyway.

> The traffic after the initial handshake is encrypted

That's normal, but traffic listener can decrypt a connection if you pass them the keys, example: https://wiki.wireshark.org/TLS

> could you provide some pointers on how to verify that HTTPS is working fine for us.

Since I don't know what you're trying to achieve, not how you're trying it, I don't know how to help you more.

I suggest to read the documentation I gave about HTTPS and TLS and more, then explain your goals, and I'll be happy to help you if I can.

Happy hacking!

**Comment by ChinmayaAgarwal** [comment]
Thank you. This helped us gaining some understanding.

**Comment by babelouest** [comment]
@ChinmayaAgarwal , can we close this issue now?

**Comment by babelouest** [comment]
I'm closing this issue now, feel free to open a new one if you need
