### ISSUE TITLE
ulfius_get_json_body_response doesn't work

### ISSUE THREAD

**Issue by Omicron360** [babelouest/ulfius#22]
Hello,

Sorry for my silence, I had difficulties with dependances. ( I work with Aix...)
Proxy evolution works, maybe add 'port' variable?

There are a problem with ulfius_get_json_body_response, if the Content-Type is "application/json; charset=UTF-8", the json body isn't loaded.
In:
	`if (response != NULL && response->map_header != NULL && NULL != o_strstr(ULFIUS_HTTP_ENCODING_JSON, u_map_get_case(response->map_header, ULFIUS_HTTP_HEADER_CONTENT)))`
	
ULFIUS_HTTP_ENCODING_JSON should be in second parameter.

**Comment by babelouest** [comment]
Yup, my mistake, I switched the parameters in `o_strstr`:
```c
char * o_strstr(const char * haystack, const char * needle);
```

In this case, haystack is the header sent back by the server.

About the `port` variable for proxy, when I added the proxy address, the libcurl documentation [specifies](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html) that `To specify port number in this string, append :[port] to the end of the host name`. I think this is better off having one proxy parameter rather than two. I'd leave it like that for now. Maybe I'll add it in a future release.

I'm glad to hear that it works on AIX without changing the code, thanks for the information!
