### ISSUE TITLE
Ulfius build on Windows

### ISSUE THREAD

**Issue by jack2007** [babelouest/ulfius#23]
Hi, I'm looking for a C restful framework, is ulfius windows ok?

**Comment by babelouest** [comment]
Actually I haven't tested Ulfius on Windows, but it might, since I don't recall to use any OS specific code, at least for the framework part, i.e. without libcurl and jansson. I don't have a windows device to test it though.

You can start with installing libmicrohttpd on windows as described in its [documentation](https://www.gnu.org/software/libmicrohttpd/), then build ulfius with the disable libcurl and jansson options:

```shell
$ # follow the installation procedure from the file INSTALL.md, then instead of a simple make command, run:
$ make CURLFLAG=-DU_DISABLE_CURL JANSSONFLAG=-DU_DISABLE_JANSSON
```

And I would be very interested by the result as well, if you don't mind.

**Comment by jack2007** [comment]
Thanks, I'll have a try and let you know the result.

**Comment by babelouest** [comment]
Also, I suggest on the first try to disable the websocket extension, it requires gnutls and libgcrypt:

```shell
$ make CURLFLAG=-DU_DISABLE_CURL JANSSONFLAG=-DU_DISABLE_JANSSON WEBSOCKETFLAG=-DU_DISABLE_WEBSOCKET
```

Don't forget in the source files, right before including ulfius header, to add the following macro:

```c
#define U_DISABLE_CURL
#define U_DISABLE_JANSSON
#define U_DISABLE_WEBSOCKET
#include <ulfius.h>
```

**Comment by babelouest** [comment]
Hi @jack2007 , did you have any luck on building ulfius for Windows?

**Comment by dominiceales** [comment]
@babelouest @jack2007 I am looking at converting the Makefile to CMake as a way to enable WIN32 (and especially VC++)  builds. At this stage I would not include curl but the JSON lib would be needed.

I'll let you know how I go...
