### ISSUE TITLE
Need better JSON example

### ISSUE THREAD

**Issue by continuum-embue** [babelouest/ulfius#24]
Really could use a simple, isolated example of proper JSON handling from within callback routines. Unclear which data structures need to be dereferenced in the call back routine itself and which data structures should not be dereferenced because you're in a callback routine and they are de-referenced elsewhere.

A simple client.c and server.c in which the client formulates a JSON message to send to the server and the server decomposes it into key-value pairs would probably do it. Extra credit if the server response builds a JSON response and the client does the same with the response.

....or point me to a  minimalist example elsewhere.

The intended data structure life-cycle is not clearly documented. The API lists the calls but doesn't explain very well how they should be ordered.

**Comment by babelouest** [comment]
Hello,

The JSON integration uses Jansson library and manipulates `json_t *` structures. There are 4 functions dedicated to import or export `json_t *` structures in the requst or the response and they are defined in the [API Documentation](https://github.com/babelouest/ulfius/blob/master/API.md#json-body-in-request-and-response).

On the server side, you have those 2 functions to manipulate JSON:

```C
/**
 * ulfius_get_json_body_request
 * Get JSON structure from the request body if the request is valid
 */
json_t * ulfius_get_json_body_request(const struct _u_request * request, json_error_t * json_error);

/**
 * ulfius_set_json_body_response
 * Add a json_t body to a response
 * return U_OK on success
 */
int ulfius_set_json_body_response(struct _u_response * response, const uint status, const json_t * body);
```

A simple example program that manipulates json is the [sheep_coounter](https://github.com/babelouest/ulfius/blob/master/example_programs/sheep_counter/sheep_counter.c) where you can see json manipulation on the server side.

Example:
```C
/**
 * Start a new counter by setting the number of sheeps to a specific value
 * return the current number of sheeps in a json object
 */
int callback_sheep_counter_start (const struct _u_request * request, struct _u_response * response, void * user_data) {
  json_t * json_nb_sheep = ulfius_get_json_body_request(request, NULL), * json_body = NULL;
  
#if JSON_INTEGER_IS_LONG_LONG
  long long * nb_sheep = user_data;
#else
  long * nb_sheep = user_data;
#endif

  if (json_nb_sheep != NULL) {
    * nb_sheep = json_integer_value(json_nb_sheep);
  } else {
    * nb_sheep = 0;
  }
  
  json_body = json_object();
  json_object_set_new(json_body, "nbsheep", json_integer(* nb_sheep));
  ulfius_set_json_body_response(response, 200, json_body);
  json_decref(json_nb_sheep);
  json_decref(json_body);
  return U_CALLBACK_CONTINUE;
}
```

If you want to manipulate json data from the client side with `ulfius_send_http_request`, the usage is quite the same, but mirrored:
```C
/**
 * ulfius_set_json_body_request
 * Add a json_t body to a request
 * return U_OK on success
 */
int ulfius_set_json_body_request(struct _u_request * request, json_t * body);

/**
 * ulfius_get_json_body_response
 * Get JSON structure from the response body if the request is valid
 */
json_t * ulfius_get_json_body_response(struct _u_response * response, json_error_t * json_error);
```

Use `ulfius_set_json_body_request` to fill the client `struct _u_request` and `ulfius_get_json_body_response` to get the json data from response if any.

My other projects use lots of json in the request and the response, you can get some inspiration from them if you want: [Glewlwyd, OAuth2 authentocation server](https://github.com/babelouest/glewlwyd) and [Hutch, password and secret locker](https://github.com/babelouest/hutch). Check the files `src/webservice.c` for the callback functions.

I also suggest you read the [Jansson Documentation](https://jansson.readthedocs.io/) to understand how to manipulate the json objects. It's a very powerful library, but some functions can be cryptic to understand at first.

**Comment by continuum-embue** [comment]
Much clearer in this context. I already followed some of your suggestions above and was able to "see" the building-block nature of the routines.  Thanks for taking the time to answer my question more directly (and more comprehensively), here.  I am sure it will help others as well.

I see now that that Jansson's json objects are completely independent and their allocation and deallocation is handled exclusively by that library. The messages are merely copied  in-and-out of ulfius structures. Consequently, it's typical to de-reference them completely within ulfius callback routines.

One last question - unrelated, but has perplexed me. There are references to o_strstr and other string functions with an "o_" prefix attached to the otherwise familiar string routine names. Where are these defined?  I am having trouble building.

**Comment by babelouest** [comment]
Absolutely, the documentation is not clear but the `json_t *` structure references are not borrowed by ulfius, so your program must allocate and free themon its own. I'll update the documentation.

Also, the json manipulation functions only transform `char *` to `json_t *` and vice versa, as you can see in the [source code](https://github.com/babelouest/ulfius/blob/master/src/u_request.c#L401).

So if you want to use another json library, feel free to do it. You can build ulfius without jansson dependency, check the `INSTALL.md` file, and then use your other library to parse and serialize JSON objects, and use directly the request and the response dedicated functions, for example:

```C
/**
 * ulfius_set_string_body_response
 * Add a string body to a response
 * body must end with a '\0' character
 * return U_OK on success
 */
int ulfius_set_string_body_response(struct _u_response * response, const uint status, const char * body);

/**
 * ulfius_set_binary_response
 * Add a binary body to a response
 * return U_OK on success
 */
int ulfius_set_binary_response(struct _u_response * response, const uint status, const char * body, const size_t length);
```

Concerning the `o_*` functions, they are the functions from [Orcania library](https://github.com/babelouest/orcania/).
As described in the [install procedure](https://github.com/babelouest/ulfius/blob/master/INSTALL.md#installation), Orcania is a library that handles some lower-level functions such as string manipulation or memory management. So that I don't have to redefine common functions in each of my projects, I prefer having them in a small library included in all the other projects.

Orcania has 3 different kinds of functions:
- Memory management functions, malloc/realloc/free functions used are the system one by default but if you want to use other memory allocation functions, you can set them with the function `void o_set_alloc_funcs(o_malloc_t malloc_fn, o_realloc_t realloc_fn, o_free_t free_fn)`
- String manipulation new functions, such as `msprintf`, `str_replace` or `split_string`
- String manipulation safe functions, such as `o_strstr` that does exactly the same as `strstr`, except that if one of the parameter is NULL, it doesn't crash the program

For all ulfius function that return a newly allocated pointer, the pointer after use (and clean if necessary) must be freed with the function `void u_free(void * data);` which calls `o_free` from orcania, which calls `free` by default or another free function that you would have defined.

**Comment by continuum-embue** [comment]
Bravo!
I think that covers it for now. I truly appreciate the time you put into this and in answering my questions. I consider your answers more than adequate to close this open issue.  Once I master this, it is my intention to use this for all of my embedded RESTful needs going forward - so I wish you a long and successful life as well.

**Comment by babelouest** [comment]
Thanks, feel free to contact me directly (the email address is in the header of each files) or open a new issue if you have problems.

**Comment by vinifr** [comment]
Hi, I have the same doubt. I am using ulfius_get_json_body_request() to retrieve body request but does not seem to work. The request is something like this:
`{
  "recordPath": "/home/vini/FL3_2018_05_07_10_20_26.wav",
  "zeroUserFile": 1,
  "startTime": "4.5",
  "zeroThreshold": "0.678",
  "peakDetectStart": "7"
}`
And i am trying to get with:
`printf("1: %s\n", json_string_value(json_nb_sheep));
      printf("2: %lld\n", json_integer_value(json_nb_sheep));
      printf("3: %s\n", json_string_value(json_nb_sheep));`

But everything is NULL or 0.

**Comment by babelouest** [comment]
@vinifr , usually, if `ulfius_get_json_body_request` returns NULL, it's because you have either a problem in your request body that is not JSON parsable, or you don't have the content-type header properly set.

It's not correctly explained in the documentation (yet), but you can use the second parameter `json_error_t * json_error` in the function `ulfius_get_json_body_request` function to have more information on the error, something like:

```C
json_error_t error;
json_t * json_nb_sheep = ulfius_get_json_body_request(request, &error);
printf("error: %s", error.text);
```
My guess is, if the body is a valid JSON string, the problem comes from the header that you can check with the following code: `u_map_get_case(request->map_header, ULFIUS_HTTP_HEADER_CONTENT)`

**Comment by vinifr** [comment]
Thanks for the reply. I have figured out the problem. We have to call json_object_get() to retrieve each value in body. Like this:
_json_string_value(json_object_get(json_nb_sheep,"recordPath"));
json_integer_value(json_object_get(json_nb_sheep,"zeroUserFile")_

**Comment by babelouest** [comment]
That's correct, thanks for the feedback.
