### ISSUE TITLE
Handing over the desired microhttpd thread model when starting framework

### ISSUE THREAD

**Issue by DeHecht** [babelouest/ulfius#27]
Hello,

I currently investigate using ulfius for my embedded system. Therefore I am interested, if it would be possible to make it possible to specify some options for the start_framework call to indicate what kind of thread-model to use in the underlying microhttpd.

To be more specific, I would like to use MHD_USE_SELECT_INTERNALLY to reduce the costs of spawning a thread for each connection.

I don't know if it would be wise to pass-through all of the microhttpd thread models blindly as I can't oversee the impact on the ulfius library in its whole.

So what is your opinion about this?

**Comment by babelouest** [comment]
Hello,

I understand the request, that was a question I asked myself at first, but since I wanted to hide libmicrohttpd complexity, I chose not to allow specific options. So I prefer using a set of options and stick to them. The MHD options Ulfius uses may be perfected, but I don't think adding `MHD_USE_SELECT_INTERNALLY` would be a good idea since it would imply rethinking the thread management. Also, I've never used this option before, so I have no idea what all the implications would be.

In your case, I'd rather modify Ulfius source code to add your options: https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L612
If you're satisfied with your modifications, I'd be glad to review a pull request in order to include it in the main branch :)

**Comment by DeHecht** [comment]
Thanks for your quick reply.

I will make a suggestion with a pull requests then. :)
