### ISSUE TITLE
[Issue]corrupted size vs. prev_size Aborted (core dumped)

### ISSUE THREAD

**Issue by alexe100** [babelouest/ulfius#275]
Ubuntu 22:

Hi,
I am looking for an efficient and optimized framework to implement websocketserver able to receive, at least the 50.000 connections/users.
I gave a try to the websocketserver sample program and used a nodejs client to create 30.000 connections (one after the other) and at the 12.071 connection the server presented:  corrupted size vs. prev_size Aborted (core dumped) and stopped.
Does ufius support lost of connections? Does ulfius uses thread based connections or some form of efficient polling?
Any ideas to extend the number of connections?

Thank a lot
Alex

**Comment by mtekllc** [comment]
50k connections on a single machine? you might easily run in to file descriptor limits.  just a FYI not a solution for you.

**Comment by alexe100** [comment]
There are reports of millions in single machine... (just returning a small string but there are)

**Comment by babelouest** [comment]
Hello @alexe100 ,

>  Does ufius support lost of connections?

Depending on what you mean by `lost of connections`, ulfius closes the connection on its side when the client is no longer connected, it doesn't keep it opened.

> Does ulfius uses thread based connections or some form of efficient polling?

Yes, by design, it uses one thread per connection.

> Any ideas to extend the number of connections?

I don't know, but I'm not sure Ulfius fits your needs, because it wasn't designed with the need for a huge amount of simultaneous connections.

I don't know what you need to do, but I agree with @mtekllc , there may also be limits on the system itself.
