### ISSUE TITLE
Adding large file upload support - improve file upload

### ISSUE THREAD

**Issue by tdphette** [babelouest/ulfius#28]
I'm currently using ulfius in an embedded project. We need to upload large files, but that doesn't appear to be currently implemented in ulflus. I was thinking I would modify ulfius to mplementing a stream reading handler, sort of the reverse of the ulfius_set_stream_response. Before I do that, I wanted to make sure I'm not reinventing the wheel and that I conform to any design or naming standards you have in case you would like to merge it back into your tree. Let me know if you have any questions or suggestions.

Thanks,

Thad Phetteplace
Software Engineer
GLACI, Inc.

**Comment by babelouest** [comment]
Hello Thad,

This is a tricky one!

The choice I made in Ulfius is to have all parameters available when the ulfius callback function is called (header, body, url, etc.). This means that if a large file is uploaded, or a large parameter value is given, it will be entirely in the ulfius application memory. Thus, uploading a large file is not recommended. That's why I added the parameters `struct _u_instance.max_post_param_size` and `struct _u_instance.max_post_body_size`, to avoid memory explosions in small systems.

But underneath, Ulfius uses a sequence of callback function calls to build the POST parameters, including the files uploaded: https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L217

I haven't tested it but one solution for could be to modify the function `mhd_iterate_post_data` in `src/ulfius.c` to call a predetermined callback function when the POST parameter is a file uploaded. I'm not sure it would work yet, but I'm sure it will work for files only, not other large POST parameters.

**Comment by babelouest** [comment]
Hello again,

I've made a patch for your request, you can test the branch [fix-for-28](https://github.com/babelouest/ulfius/tree/fix-for-28).

To use it, you must call the following function after initializing your `struct _u_instance`:
```c
int ulfius_set_upload_file_callback_function(struct _u_instance * u_instance, int (* file_upload_callback) (const struct _u_request * request, 
                                                       const char * key, 
                                                       const char * filename, 
                                                       const char * content_type, 
                                                       const char * transfer_encoding, 
                                                       const char * data, 
                                                       uint64_t off, 
                                                       size_t size, 
                                                       void * cls), void * cls);
```

then, the function `file_upload_callback` will be called in a sequence. In that function, you have access to the `struct _u_request`, but not necessarily complete, i.e. some parameters may be missing from the `struct _u_request` that will be passed to the ulfius callback functions.
The parameter `* cls` is defined when you call `ulfius_set_upload_file_callback_function`. So, basically, it's not sync with the `void * user_data` in the ulfius callback function, that's because since you can have multiple callback functions for the same HTTP address, and each of them can have a different `user_data`, Ulfius wouldn't know what `user_data` to pass to `file_upload_callback`, thus, here's a new one.
The return value of the function must be `U_OK`, otherwise, you will send an error signal that will cancel the POST parameters processor.

Also, be aware that your file upload callback function `file_upload_callback` will always be called before the ulfius callback functions.

Let me know if you have some questions or feedback.

**Comment by tdphette** [comment]
Yes, I've already did a bit of hacking on ulfius_webservice_dispatcher and mhd_iterate_post_data and verified that I can hook into the post stream. I haven't yet actually exposed that to the API in any useful way. My current thinking was to set up post processing callbacks for specific endpoints during initialization when I'm adding the endpoints. The trick is to make sure I capture the post stream before the main callback but after the authentication, since I don't want to let an unauthorized user upload anything. Unfortunately, it looks like the auth check happens after the post stream is processed by ulfius_webservice_dispatcher. I'm still trying to figure out a clean way to handles this that isn't a total kludge.

**Comment by tdphette** [comment]
Looks like you sent a response will I was typing my last message. I'll give the fix a try. Thanks!

**Comment by babelouest** [comment]
Sure, just a small change: the branch is now called `large-file-upload` instead of `fix-for-28`, it's more eloquent like that.

**Comment by tdphette** [comment]
I gave it a try but didn't see the behavior I was expecting. Using the sheep_counter example as a reference, I added an upload file callback and then posted a file to my program. My debug messages show the full 80K post being sent to ulfius_webservice_dispatcher, but only the first few hundred bytes are sent to the upload handler.

After digging around in the ulfius source code a bit, I think I found the issue. I moved the MHD_post_process call to a different place in ulfius_webservice_dispatcher and changed the parameters to pass the entire upload_data buffer. This works for the upload case, though I haven't checked if it breaks things in other cases.  Here is the change I made in ulfius.c to get it working:

```
    if (body_len >= con_info->request->binary_body_length) {
      printf("TDP-ulfius: body_len >= binary_body_length\n");
      con_info->request->binary_body = o_realloc(con_info->request->binary_body, body_len);
      if (con_info->request->binary_body == NULL) {
        y_log_message(Y_LOG_LEVEL_ERROR, "Ulfius - Error allocating memory for con_info->request->binary_body");
        return MHD_NO;
      } else {
        memcpy((char*)con_info->request->binary_body + con_info->request->binary_body_length, upload_data, upload_data_size_current);
        con_info->request->binary_body_length += upload_data_size_current;

        /* Moved this from below and changed to send entire upload_data buffer */
        MHD_post_process (con_info->post_processor, upload_data, *upload_data_size);

        *upload_data_size = 0;
        return MHD_YES;
      }
    } else {
      printf("TDP-ulfius: body_len not longer\n");
      return MHD_YES;
    }

```

**Comment by babelouest** [comment]
It took me a little while but I understood your patch.

I haven't tested it yet but this seems correct for the new feature. Before, the function `MHD_post_process` was called after the request body was processed, I forgot about that. So in your case, the body was still entirely present in memory before calling `MHD_post_process`, leading to memory explosion...
Thanks for pointing out. :)

I'll keep the if `content_type` check though, like this:
```c
    const char * content_type = u_map_get_case(con_info->request->map_header, ULFIUS_HTTP_HEADER_CONTENT);
    if (0 == o_strncmp(MHD_HTTP_POST_ENCODING_FORM_URLENCODED, content_type, strlen(MHD_HTTP_POST_ENCODING_FORM_URLENCODED)) || 
        0 == o_strncmp(MHD_HTTP_POST_ENCODING_MULTIPART_FORMDATA, content_type, strlen(MHD_HTTP_POST_ENCODING_MULTIPART_FORMDATA))) {
      MHD_post_process (con_info->post_processor, upload_data, *upload_data_size);
    }
```

**Comment by tdphette** [comment]
Very cool. Thanks for working on this feature. I still have the issue that the authentication handler is called after file upload is processed, but I understand the design decisions that make that necessary. I can work around it by having the upload handler directly call the function that checks the auth token.

**Comment by babelouest** [comment]
Can you test this commit: https://github.com/babelouest/ulfius/commit/8c715d1d9973fe6b97ccab2280c52326a29aca76 ?

I'll run some tests on my side and re-run all the unit tests of all the existing applications that use Ulfius to make sure nothing is broken.

**Comment by tdphette** [comment]
It worked after one minor change. I think upload_data_size should be set to zero after the call to  MHD_post_process, not before.  This is what I changed to make it work:

```
        // Handles request binary_body
        const char * content_type = u_map_get_case(con_info->request->map_header, ULFIUS_HTTP_HEADER_CONTENT);
        if (0 == o_strncmp(MHD_HTTP_POST_ENCODING_FORM_URLENCODED, content_type, strlen(MHD_HTTP_POST_ENCODING_FORM_URLENCODED)) || 
            0 == o_strncmp(MHD_HTTP_POST_ENCODING_MULTIPART_FORMDATA, content_type, strlen(MHD_HTTP_POST_ENCODING_MULTIPART_FORMDATA))) {
          MHD_post_process (con_info->post_processor, upload_data, *upload_data_size);
        }
        *upload_data_size = 0;
```

**Comment by babelouest** [comment]
My bad :p
https://github.com/babelouest/ulfius/commit/b05cba347d6d98b633c1eb87879668a2d3fb1aae

**Comment by babelouest** [comment]
Hello @tdphette ,

I've completed all the tests I have on my side, the patch doesn't seem to break anything, however, my tests are when `ulfius_set_upload_file_callback_function` isn't used.
I will soon run a test batch with `ulfius_set_upload_file_callback_function` to validate this functionality.

Did you have time to test the branch for your requirements?

**Comment by tdphette** [comment]
Absolutely. I'll probably even demo it to my coworkers in a few days. They are interested in seeing this work, Thanks again for your help.  :)

**Comment by babelouest** [comment]
Hello @tdphette , as far as I can tell, the new functionality is complete, I've merged the pull request and I'm closing this issue. Thanks again for your help!
