### ISSUE TITLE
General discussion about Ulfius and its next features

### ISSUE THREAD

**Issue by silvioprog** [babelouest/ulfius#34]
Hi dudes.

Please sorry if it was an irrelevant sharing, but I've shared Ulfius at MHD's list in a topic regarding GSoC (Google Summer of Code):

http://lists.gnu.org/archive/html/libmicrohttpd/2018-01/msg00006.html

IMHO, Ulfius is the best and prepared project using MHD that should be presented in that event, and it is very easy to learn too.

I'm not familiar with GSoCs because I've never participated one, but I think that anything shown in these Google events get its ecosystem growing more and more.

Thank you!

**Comment by babelouest** [comment]
Hello @silvioprog ,

Thansk a lot for the initiative. Although I'm not sure GSoC is an event where you can present open-source projects.

As far as I know, GSoC is an initiative from Google to help open-source projects. You have to submit an improvement to GSoC, the improvement must be specific on what project will be improved and what new features are expected. You can submit multiple improvements for the same project though. If an improvement is accepeted by GSoC, they will give money to the project and the developper assigned to this improvement, usually a student, that's why it's called Google Summer of Code, so student can work on the project outside of his/her stidy time.

I'm glad that you like Ulfius and would like to make some publicity about it. Maybe there are other ways to spread the word though, but I don't really know which one right now.
I'm programming Ulfius on my free time and for my own use, but I'm not a fundation or a company, so Ulfius is not really GSoC matierial I think.

Maybe there are other events or media where Ulfius could be introduced, to spread the word and show Ulfius to people that would be interested. I'll think about that in the future.

**Comment by babelouest** [comment]
[Google Summer of Code](https://en.wikipedia.org/wiki/Google_Summer_of_Code) is more understandable.

**Comment by silvioprog** [comment]
Hello @babelouest . :-)

I need to tell somethings and make some questions, to help me in an important decision.

Some time ago I created the [Brook4RET library](https://github.com/brook-dev/brook4rest). Its main purpose is:

* easy to use, like a NodeJS (just its HTTP support, because I'm one of those guys who likes to use JS only in front-end :sunglasses: );
* use modern concepts in the server, like event-driven instead of thread-based;
* offer at least one binding for [Delphi](https://www.embarcadero.com/products/delphi) and [Lazarus](https://www.lazarus-ide.org) tools (actually I'm very inclined to create a C++ binding too);
* build on Linux(ARM) and Windows 32/64 (with [single DLL](http://brook.no-ip.org/download/libbrook-4.dll) and its [signature file](http://brook.no-ip.org/download/libbrook-4.dll.sig) for Windows version);
* build for Android using Android Studio's builtin CMake support;
* help a [popular legacy Pascal-only framework that I maintain](https://github.com/silvioprog/brookframework) to be more modern and fast; (allowing it to run via something like HTTP proxying or FastCGI)
* great stability and performance (sure!).

all topics above are fixed using [MHD library](https://www.gnu.org/software/libmicrohttpd) and CMake. But, the Brook's library have other specific features, and some of them are already implemented in Ulfius project:

* routing (using something like [libFFI](https://sourceware.org/libffi), allowing the library to easily call functions from other programming languages; **[partially present in Ulfius - partially just because I'm not sure which FFI structure it uses]**
* regex support in the routing (something like [Express](http://expressjs.com/en/guide/routing.html) one);  **[partially present in Ulfius - partially just because I'm not sure about regex support]**
* REST structure with JSON support (using something like jansson or libjson); **[present in Ulfius]**
* fast string handling with [hash table](https://troydhanson.github.io/uthash) in any part with key-value structure (eg. headers, parameters, fields etc.); **[partially present in Ulfius - partially just because I'm not sure about `u_map` performance comparing to a [key-value hashed structure](https://troydhanson.github.io/uthash/userguide.html#hash_functions)]**
* safe magic ID per request (an important feature that I implemented -- that can be improved, sure. I can explain with with more details in other comment); **[present in Brook and could be easily ported to Ulfius]**
* byte-serving support (allowing to upload/download large files with pause/continue support); **[partially implemented by me in a draft inspired by RFC's examples and nginx implementation]**
* i18n support (something like one I suggested for MHD and was deeply improved by [Christian Grothoff](https://grothoff.org/christian/)); **[present in Brook using same MHD's i18n style]**
* OAuth/JWT support (currently I'm using only basic auth); **[present in Ulfius with an awesome front-end]**
* plugins (to easily extend the library features with external libraries (something like [SQLite's run-time extensions](https://www.sqlite.org/loadext.html) / [nginx's dynamic modules](https://www.nginx.com/blog/nginx-dynamic-modules-how-they-work/))). **[for while, not implemented neither Brook or Ulfius]**

Certainly, there is other topics I forgot, but these above are the most important. Then, what I have in mind along all this? Join with someone that shares the same ideas. I didn't know Ulfius when I created Brook, maybe because missing announcements/marketing, but, after studying it, it seems the project that Brook is closest in many features. So, my intention is to take Brook to Ulfius, but I have some features (showed in the topics above) that I cannot leave. So, my question is: do you have interest in doing that? If so, I could make Brook4REST just a power binding for Delphi/Free Pascal/C++(and others in a near future), because my only concerns would help to improve the Ulfius core, building and cross platform support.

Anyway, I want that Ulfius grow more and more, because somehow I feel like a member of the project and it will be part of my work, so I intend to continue helping the project (currently on its building).

**Comment by babelouest** [comment]
Hello @silvioprog ,

That's an interesting which needs some thinking and discussions. I'm totally OK about having more interested people contributing to it, that's why I published it with an open-source license.

One thing is important to me in Ulfius, it's keeping the the KISS principle, so in my opinion, some of the features you'd like to add are too overkill for Ulfius. To me it should stay as a web framework only, but I don't see why it could have some connectors so external features could be added by third-party developers.

More precisely:
- routing: I'm wondering if this could be done as another library, I made Ulfius out of libmicrohttpd, using the same way, maybe someone can make a routing library out of Ulfius, both will be integrated but you could use Uifius core without needing routing
- regex: I thought about it when I made Ulfius 2.0, but eventually I thought it would be too complicated for my needs, so I kept my basic parsing instead. But if you have ideas on how to implement it and how it would work, I'm interested.
- fast string handling: interesting, I made the `struct _u_map` to meet my small needs and because I knew it wasn't long to make. `utash` seems very lightweight though, it would interesting to integrate it in Ulfius array structures
- safe magic ID per request: please explain it a little bit?
- byte-serving support: it there a standard to explain the implementation this like a RFC for this? Maybe a good idea would be to facilitate the implementation for the developer, with some examples, but not implementing it in Ulfius
- i18n support: can you explain your needs on this and what would be the result in Ulfius?
- OAuth/JWT support: Actually, it's not implemented /in/ Ulfius, [Glewlwyd](https://github.com/babelouest/glewlwyd) is an OAuth2 authentication server that provides JWT but the authentication part is implemented /with/ ulfius, not by. I added as reusable callback functions the OAuth2 authentication check but I don't consider it part of Ulfius
- plugins: also a good idea, but not necessarily part of Ulfius, more as a third-party library that would have Ulfius as a dependency

So what I would suggest is implementing some features, but the other ones can be implemented as external tools that would have Ulfius in their dependencies.

By doing this, you could make a bigger framework where one of its element is Ulfius. I like the Unix principle where you have small tools that do one thing and interact with other tools, that's why I made one library for the HTTP interface and another for the database.

**Comment by mickae1** [comment]
please add openssl in option build for the https connection .

**Comment by babelouest** [comment]
@mickae1 , the https connection is managed by `libmicrohttpd`, not Ulfius itself.
If you need to use https connections with openssl (i.e. `libssl`), you need to build libmicrohttpd with openssl instead of gnutls.

As far as I can see, the openssl feature request in libmicrohttpd is [quite old](https://lists.gnu.org/archive/html/libmicrohttpd/2016-08/msg00009.html) and still not done. If you're willing to offer your help to the libmicrohttpd team, they'll be happy I guess!

**Comment by babelouest** [comment]
I'm closing this issue, new features can be discussed in the [discussion](https://github.com/babelouest/ulfius/discussions) tab.
