### ISSUE TITLE
Ulfius is now available in AUR for Archlinux

### ISSUE THREAD

**Issue by FedeDP** [babelouest/ulfius#51]
Hi!
Thanks for this awesome piece of work! I still haven't got time to dig into the implementation, but the API is really great!
I recently pushed a package to the AUR for Archlinux with your latest release, you can find it here: https://aur.archlinux.org/packages/libulfius/ .
So you can add Arch to the list of supported OS!
I'd like to ask you about orcania and yder though: must they be forcedly built? I mean, i am having some issues initing git submodules from a github release tarball, so i wonder whether these 2 submodules are really mandatory and what i'd miss if i do not package them.

Again, thank you very much!

**Comment by babelouest** [comment]
Thank you very much, this is highly appreciated!

Concerning orcania, this is a lower-level library that handle string-related functions like `o_strcmp` or `o_strdup`. They are mostly shelves for the original function but they don't crash if one of the parameter is NULL, see [o_strcmp](https://github.com/babelouest/orcania/blob/master/src/orcania.c#L130) for example.
Orcania also has functions to [split a string into an array of strings](https://github.com/babelouest/orcania/blob/master/src/orcania.c#L329).
And finally, orcania allows to use [other](https://github.com/babelouest/orcania/blob/master/src/memory.c) `malloc` functions than the good old `malloc`. This can be useful in some environments where other memory managements are required.

Yder is a small [logging library](https://github.com/babelouest/yder) that has 3 public functions available: `y_init_logs`, `y_log_message` and `y_clos_logs`. It was a better way to log messages than printf or syslog.

I externalized those libraries because I use them as well in [hoel](https://github.com/babelouest/hoel), my database abstraction library and in my applications like [gewlwyd](https://github.com/babelouest/glewlwyd).

I would recommend to package orcania and yder independently, because if you or someone else wants to package hoel or glewlwyd or taliesin, any other project that requires orcania and yder, they will have to include them statically like you did.

Although I won't force you to, and it doesn't change the fact that I'm very happy with your contribution, thanks again!

**Comment by FedeDP** [comment]
This seems like a good idea (honestly i already thought about that)!
I will split the packages as soon as possible, and report here back :)

**Comment by FedeDP** [comment]
@babelouest 
All three packages are now up on AUR:
* [orcania](https://aur.archlinux.org/packages/liborcania/)
* [yder](https://aur.archlinux.org/packages/libyder/)
* [ulfius](https://aur.archlinux.org/packages/libulfius/)

Thank you very much for this software :)

**Comment by AaronBottegal** [comment]
Just in time, I need something like this and installed from the AUR just fine. Thanks!
