### ISSUE TITLE
Improve pkg-config support

### ISSUE THREAD

**Issue by mnhauke** [babelouest/ulfius#62]
The pkg-config file should list all the requirements needed for the library.

See:
https://people.freedesktop.org/~dbn/pkg-config-guide.html#faq

Here's an example from another project:
https://github.com/realnc/SDL_audiolib/blob/master/CMakeLists.txt
https://github.com/realnc/SDL_audiolib/blob/master/SDL_audiolib.pc.in

The same applies to your other libraries (ocania,..).

**Comment by babelouest** [comment]
Thanks for the pointer

I'm not sure I understand the difference between `Requires` and `Requires.private` though (and the other `*.private` values as well).

In your example, both values are the same, and the `pkg-config` documentation says:
```
* Requires: A list of packages required by this package. The versions of these packages may be specified using the comparison operators =, <, >, <= or >=.
* Requires.private: A list of private packages required by this package but not exposed to applications. The version specific rules from the Requires field also apply here.
```

Does it mean in ulfius case that the values would be something like?
```
Requires: libmicrohttpd, jansson, gnutls, libc6, libcurl, yder, orcania
Requires.private: libmicrohttpd, gnutls, libc6, libcurl
```

Since Jansson, Yder and Orcania functionalities are exposed to applications that use ulfius.

**Comment by babelouest** [comment]
If I understand correctly the documentation, the master branches of Orcania, Yder, Ulfius and Hoel should now have correct values for pkg-config.
