### ISSUE TITLE
why using https://travis-ci.com/babelouest ?

### ISSUE THREAD

**Issue by chipitsine** [babelouest/ulfius#77]
there's https://travis-ci.org which is free for open source projects

**Comment by babelouest** [comment]
I didn't know,  I'll switch asap

**Comment by babelouest** [comment]
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
Since may 2018, travis-ci.com has opened its doors for open-source projects for free (that's the account I have) and they will be migrating projects from travis-ci.org to travis-ci.com.

So I think that moving to travis-ci.org isn't relevant anymore...
