### ISSUE TITLE
http redirection

### ISSUE THREAD

**Issue by vineyyadav** [babelouest/ulfius#86]
Hi,
I have setup an https://<some_url> server using Ulfius and all works well. What I want is to add a redirection so that opening http://<some_url> redirects to https://<some_url>

One method I could think of was to start 2 instances of Ulfius webservice, one on port 443 for actual serving and another on port 80 which redirects all requests to https.

Could there be some better way to achieve this e.g. with a single instance of Ulfius.
Thanks

**Comment by babelouest** [comment]
Hello @vineyyadav ,

Unfortunately, Ulfius can't listen to more than 1 port by design, so you'd have to run another ulfius instance to redirect all `http://<server>:80/` calls to `https://<server>:443/`.
Something with `response->status = 3xx` and the same url than the request in the header `Location: /url/`.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

Although concerning my ulfius instances, when they are available from outside of my network, I use apache mod http_proxy to protect them a little bit more and facilitate administration tasks.
