### ISSUE TITLE
Thread synchronisation

### ISSUE THREAD

**Issue by Oozlum** [babelouest/ulfius#87]
I would like to use Ulfius to provide a WebSockets command/control API for a server process, but I am unsure how to manage the synchronisation between the server and Ulfius threads -- it's unclear from the documentation in which order the various API callbacks are called and from which threads.

In particular, the main server thread would need a way to signal that new data is available to be pushed to any connected clients, but it is not clear how the WebSocket manager callback is integrated into whatever event loop is running and how to achieve that.  ~~The websocket_server example seems to push new data to the client every second, but it isn't clear from where that is controlled.~~ (Edit: I didn't see the sleep() statements, sorry.)

Do you have any examples that would help with this?

**Comment by babelouest** [comment]
Hello @Oozlum ,

I'll try to explain how the websockets threads are designed. I assume you have read Ulfius websocket documentation in the [API](https://github.com/babelouest/ulfius/blob/master/API.md#websockets-communication).

When your program accepts a websocket connection from a client, Ulfius framework opens a master thread that you don't have access to.
This thread manages the connection between your program and the client, and closes the websocket when asked to or when the connection is broken.

When you create a websocket response, if you set a `websocket_manager_callback`, then a thread will be opened by the master thread above.
The `websocket_manager_callback` function is running at the beginning of your websocket connection, it will contain your algorithm and logic of what you want to do with the websocket service. When your code will end this `websocket_manager_callback` function, the websocket manager thread will close the websocket and end the connection with the client.

If you set a `websocket_incoming_message_callback` function, this function is executed in the same thread than the master thread. It will be executed every time the websocket receives a message from the client. This function isn't executed in a separated thread, so you can't have 2 running at the same time.

That's for the threads in the websockets. But apparently, you need to understand how to send a websocket message from outside of the websocket callback functions. That's what the `websocket_*_user_data` are for.

I'll describe a use case to help you understand.

Lets's say your program reads a log file and sends each new log line to all connected clients via their websockets whenever they arrive.

You can design it with a data structure that will contain the signal handler and the message to send:

Then, in your `main()` function, you create a `struct log_signal` with `malloc`, and pass the new pointer as `websocket_manager_user_data` value. The following pseudo-code will help you unerstand what I mean:
```C
struct log_signal {
  pthread_mutex_t websocket_signal_lock;
  pthread_cond_t websocket_signal_cond;
  char * message;
}

int main() {
  // [...]
  struct log_signal * my_signal = malloc(sizeof(struct log_signal));
  // initialize my_signal.websocket_signal_lock and my_signal.websocket_signal_cond
  // [...]
  ulfius_add_endpoint_by_val(&instance, "GET", NULL, "websocket", 0, &callback_get_websocket, my_signal);
  // start instance
  char * log_line;
  while (1) {
    log_line = get_new_log_line();
    // a new log line has appeared
    pthread_mutex_lock(&my_signal ->websocket_signal_lock);
    pthread_cond_broadcast(&my_signal ->websocket_signal_cond);
    pthread_mutex_lock(&my_signal ->websocket_signal_lock);
  }
}

int callback_get_websocket (const struct _u_request * request, struct _u_response * response, void * user_data) {

  if ((ret = ulfius_set_websocket_response(response, NULL, NULL, &websocket_manager_callback, user_data, NULL, NULL, NULL, NULL)) == U_OK) {
    return U_CALLBACK_CONTINUE;
  } else {
    return U_CALLBACK_ERROR;
  }
}

void websocket_manager_callback(const struct _u_request * request,
                               struct _websocket_manager * websocket_manager,
                               void * websocket_manager_user_data) {
  while (1) {
    pthread_mutex_lock(&((struct log_signal *)websocket_manager_user_data)->websocket_signal_lock);
    pthread_cond_wait(&((struct log_signal *)websocket_manager_user_data)->websocket_signal_cond);
    pthread_mutex_unlock(&((struct log_signal *)websocket_manager_user_data)->websocket_signal_lock);
    // New line arrived
    if (ulfius_websocket_send_message(websocket_manager, U_WEBSOCKET_OPCODE_TEXT, strlen(((struct log_signal *)websocket_manager_user_data)->message), ((struct log_signal *)websocket_manager_user_data)->message) != U_OK) {
      printf("Error sending websocket message\n");
    } else {
      printf("Websocket message sent\n");
    }
  }
}
```

There are other solutions like using the `websocket_manager_user_data` for a structure that will contain an array of `struct _websocket_manager *`, and in `websocket_manager_callback`, you append the current pointer `struct _websocket_manager * websocket_manager` to this array. Then, like above, the pointer `websocket_manager_user_data` will be shared with the `main()` thread, so in this thread you can call `ulfius_websocket_send_message` with each `struct _websocket_manager * websocket_manager`  you have in your array.

Does it answer your question?

**Comment by Oozlum** [comment]
Thank you, that answers the question perfectly.  I think the mutex locking and unlocking is incorrect in both main() and websocket_manager_callback() -- the callback would lock the mutex then wait indefinitely? -- however, it is more than enough to understand the principle.

If I call ulfius_websocket_send_message() from the main() thread, will Ulfius manage any synchronisation internally, or am I responsible for that too?  (I'm not talking about user data here, but the actual API call itself.)

Also, are the y_log* and u_map functions thread safe, or do they need to be guarded?

**Comment by babelouest** [comment]
I know that a `pthread_mutex_t` is mandatory to use a `pthread_cond_t`. In the documentation and examples I read, they always lock the mutex before waiting for the signal or sending a signal, then they unlock the mutex.
Although the mutex isn't initialized the same as  when it's used by itself to safely lock resources.

See [here](https://github.com/babelouest/ulfius/blob/master/src/ulfius.c#L1312) for a mutex initialized for a cond: no mutex attribute.
And see [here](https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L1268) for a mutex initialized to lock resources between threads: mutex attribute set to `PTHREAD_MUTEX_RECURSIVE`.

I have implemented an example of websockets synchronization in Taliesin if you're curious:
https://github.com/babelouest/taliesin/blob/master/src/webservice.c#L1421
It behaves the same way I described it in my example below.

If you don't want your `pthread_cond_t` to block forever until a signal is sent, you can use `pthread_cond_timedwait` instead of `pthread_cond_wait`.

If you call `ulfius_websocket_send_message` from any thread of your application, it will be [thread-safe](https://github.com/babelouest/ulfius/blob/master/src/u_websocket.c#L267).

Concerning the other functions, `y_log_message` should be thread-safe. `y_init_log` and `y_close_logs` are not thread-safe but they should not be executed outside of the `main()` thread.

The `u_map` functions are not designed to be thread-safe, if you use `u_map_put` at the same time in different threads for the same `struct _u_map *`, it may behave incorrectly. But in my design, `struct _u_map *` variables are not supposed to be used outside of the callback functions. I haven't found a use case where it could be useful. If necessary, I create another thread-safe structure that is used to fill the `struct _u_map`.

**Comment by Oozlum** [comment]
Thank you.
