### ISSUE TITLE
CMake packaging bug

### ISSUE THREAD

**Issue by Oozlum** [babelouest/ulfius#89]
I'm building with CMake and using 'make package' for the generated .tar.gz file.  If I manually specify the libdir with -DCMAKE_INSTALL_LIBDIR then the library files are no longer packaged in the .tar.gz file:

`cmake -DCMAKE_INSTALL_LIBDIR=/usr/lib -DWITH_CURL=off -DWITH_JOURNALD=off -DBUILD_UWSC=off
make && make install package` 

Without -DCMAKE_INSTALL_LIBDIR all files are included.

**Comment by babelouest** [comment]
Hi @Oozlum ,

Thanks for the report. As far as my understanding goes, you should not set `CMAKE_INSTALL_LIBDIR` because it's build by cmake script on execution and is a relative path.

To my knowledge, using the variable `CMAKE_INSTALL_PREFIX` is better.

If I'm mistaking, please explain your needs describe your use case.

I can reproduce your bug but I'm not yet sure it's a bug.

**Comment by Oozlum** [comment]
I’m trying to install in a system that doesn’t understand Multi-arch libdirs (lib64), so I’m trying to override it to install in the usual `/usr/lib` location. `CMAKE_INSTALL_PREFIX` won’t achieve that.

Also, it would be nice if there was a way to exclude the `/usr/share` stuff from the package.

**Comment by Oozlum** [comment]
Thanks, I’ll try that.

Excluding files isn’t too much of an issue. I can always exclude when untarring. It’s a pity there isn’t a CMAKE_INSTALL_DOCDIR, otherwise I could use this feature to good effect... /s

**Comment by babelouest** [comment]
The examples install already use `CMAKE_INSTALL_DOCDIR`:
https://github.com/babelouest/ulfius/blob/master/CMakeLists.txt#L325
https://github.com/babelouest/ulfius/blob/master/CMakeLists.txt#L327
