### ISSUE TITLE
Request for new feature:support for uploading files in auth_example

### ISSUE THREAD

**Issue by akhileshsarda** [babelouest/ulfius#99]
Hi, 
I tried putting relevant code of uploading files in auth_example.
There I came across one problem, How to use browser for auth_example?
I mean, I'll have to keep certificates in browser.(able to import only ca certificate)
But it didn't work. (I think server is not receiving clients certificate)

And I could't use curl command as well (certificate issue)
Any idea how can i resolve ?

**Comment by babelouest** [comment]
I'm not sure I understand your feature request.
What is the problem you want to resolve?

Also, can you post a sample code to explain what you want to achieve?

**Comment by akhileshsarda** [comment]
Consider the following scenario:
I have ./auth_server running on my terminal (with certificates). This auth_server
contains only one callback which is "callback_auth_client_cert", just serve the client.

On other side, instead of running auth_client on terminal (to request server), I want to make request from 
browser (https://localhost:2884/auth/client_cert). Now, server has to respond and browser should show the response message.
Did you get me?

**Comment by babelouest** [comment]
This already is how it works. The `auth_server` program answers to any http client.

If you access [https://localhost:2884/auth/client_cert](https://localhost:2884/auth/client_cert) with your browser, you will have a different message wether you're navigating with a client certificate or not.

To use client authentication with your browser, you must install your certificate in the browser first. In Firefox it's something like this.

![install certificate](https://www.digicert.com/images/2fa-images/browser-images/export-certificate-firefox-mac-1.png)

**Comment by babelouest** [comment]
@akhileshsarda , did you move forward with my anser to your request?

**Comment by akhileshsarda** [comment]
Were you able to import client.crt file there ?
I couldn't.

While uploading client certicates it was giving error (like missing private key), same 
while uploading client key it showed invalid/corrupt file.
So, tried concatenating both (client.crt and client.key ) and converted into PFX format using following single command :
`openssl pkcs12 -export -out certificate.pfx -inkey client.key -in client.crt`
Then uploaded this .PFX file in "your  certificates" column of browser which worked for me.
Anyways now I am able to upload files to secured server using browser.

By the way, Did you try posting or fetching(GET) using curl command in case of server is authenticating client?
I tried like this: `curl --cert client.crt --key client.key https://loclahost:2884/auth/client_cert`

**Comment by babelouest** [comment]
In `auth_example`, the url `/auth/client_cert` accepts only the `GET` method.

There is an [example of how to generate](https://github.com/babelouest/ulfius/blob/master/example_programs/auth_example/auth_client.c#L12) the set of certificates you can use for your tests in the same example. But as I explain in this example, this is suited for local tests only.
If you need to generate a set of certificates and keys for production, read carefully the certificate generator documentation.

As for your issue on importing the certificate in the browser, I don't see how it's Ulfius related. You'll have better luck reading the online documentation on how to use client certificates on your browser, but I can't help you more with that because I'm not an expert on those questions.

I also invite you to read documentation about TLS handshake with client certificate, like [this one](https://blog.cloudflare.com/introducing-tls-client-auth/) for example, because it seems that you mix up the responisibility of each part in the client certificate authentication.

**Comment by akhileshsarda** [comment]
Okay !
Anyways the stuff is working now.
So, we can close the issue.
Thanks for the help !
:+1:
